#! /bin/bash
#
# Usage:
#
# 	./upload main_file.c
#
# This calls build main_file.c and uploads img.hex to /dev/ttyUSB0

./build $@ && \
avrdude -v -p atmega328p -c arduino -P /dev/ttyUSB0 -b 57600 -D -U flash:w:img.hex:i
